<?php

/**
 * @file
 * Contains oracle_provider.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function oracle_provider_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the oracle_provider module.
    case 'help.page.oracle_provider':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides a service in order to perform queries to Oracle Database') . '</p>';
      return $output;

    default:
  }
}
